version: 2.1

orbs:
  slack: circleci/slack@4.4.4

wordpress-version-matrix: &wordpress-version-matrix
  matrix:
    parameters:
      wp-version: [ "5.5", "5.7.2", "5.8"]

workflows:
  lint-test-and-build:
    jobs:
      - functional-tests:
          <<: *wordpress-version-matrix
          filters:
            branches:
              ignore: /^.*-built$/

      - approve-build:
          type: approval
          requires:
            - functional-tests
          filters:
            branches:
              only:
                - master
#       - build:
#           type: approval
#           requires:
#             - functional-tests
      - deploy-build:
          requires:
            - approve-build

jobs:
#   approve-build:
#     docker:
#       - image: circleci/php:7.4-browsers
#     steps:
#       - checkout
#       - run:
#           name: approve build
#           command: |
#             echo "approve build"

  deploy-build:
    docker:
      - image: circleci/php:7.4-browsers
    steps:
      - checkout
      - run:
          name: deploy build
          command: |
            echo "deploy build"


  functional-tests:
    docker:
      - image: cimg/base:2021.01
    parameters:
      wp-version:
        type: string
        default: latest
    steps:
      - checkout
      - run:
          name: echo this
          command: python3 .circleci/things.py
      - run:
          name: echo this
          command: |
            python --version
             $(.circleci/things.py)

      - run:
          name: is this working
          command: |
            echo " wp version << parameters.wp-version >> "
            echo "in functional tests"
#      - slack/notify:
#          custom: |
#            {
#              "blocks": [
#                {
#                  "type": "section",
#                  "fields": [
#                    {
#                      "type": "plain_text",
#                      "text":"here we need to add ze text"
#                      "emoji": true
#                    }
#                  ]
#                }
#              ]
#            }
#          event: always

