version: 2.1

orbs:
  slack: circleci/slack@4.4.4

wordpress-version-matrix: &wordpress-version-matrix
  matrix:
    parameters:
      wp-version: [ "5.5", "5.7.2", "5.8"]

workflows:
  lint-test-and-build:
    jobs:
      - functional-tests:
          context: slack
          <<: *wordpress-version-matrix
          filters:
            branches:
              ignore: /^.*-built$/
      - staging-build:
          context: slack
          requires:
            - functional-tests
          filters:
            branches:
              only:
                - master
      - approve-build:
          type: approval
          requires:
            - staging-build
          filters:
            branches:
              only:
                - master
      - deploy-build:
          context: slack
          requires:
            - approve-build
          filters:
            branches:
              only:
                - master

jobs:
  staging-build:
    docker:
     - image: circleci/php:7.4-browsers
    steps:
     - checkout
     - slack/notify:
#         channel: "general"
         channel: C02HK0YTJFP
         custom: |
           {
             "blocks": [
               {
                 "type": "section",
                 "text": {
                   "type": "plain_text",
                   "text": "Hi all, we are about to release the following to production \n $(.circleci/get_on_hold_commit_messages.py | tr ';' 'blah blah blah')",
                   "emoji": true
                 }
               }
             ]
           }
         event: always


  deploy-build:
    docker:
      - image: circleci/php:7.4-browsers
    steps:
      - checkout
      - run:
          name: deploy build
          command: |
            echo "deploy build"
      - slack/notify:
#          channel: "general"
          channel: C02HK0YTJFP
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "plain_text",
                    "text": "Hi all, we have now deployed the following to production \n $(.circleci/get_on_hold_commit_messages.py | tr ';' '\n')",
                    "emoji": true
                  }
                }
              ]
            }
          event: always
      - run:
          name: cancel on_hold workflows
          command: .circleci/cancel_workflow.py

  functional-tests:
    machine:
      image: ubuntu-2004:202104-01
    parameters:
      wp-version:
        type: string
        default: latest
    steps:
      - checkout
      - run:
          name: Set Python version
          command: |
              pyenv global 3.9.4
              python --version
      - run:
          name: is this working
          command: |
            echo " wp version << parameters.wp-version >> "
            echo "in functional tests"
